### ISSUE TITLE
error timetree request

### ISSUE THREAD

**Issue by Kritchyyui** [blab/norovirus#1]
I attempted to reproduce your data, but encountered the following error. Could you please assist me in resolving this issue?
[Wed Oct  9 04:38:59 2024]
Error in rule refine:
    jobid: 447
    input: results/GII.4/genome/tree_raw.nwk, results/GII.4/genome/aligned.fasta, results/GII.4/genome/filtered_metadata.tsv
    output: results/GII.4/genome/tree.nwk, results/GII.4/genome/branch_lengths.json
    shell:
        
        augur refine             --tree results/GII.4/genome/tree_raw.nwk             --root "best"             --clock-filter-iqd 4             --alignment results/GII.4/genome/aligned.fasta             --metadata results/GII.4/genome/filtered_metadata.tsv             --output-tree results/GII.4/genome/tree.nwk             --output-node-data results/GII.4/genome/branch_lengths.json             --timetree             --date-confidence         
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

[Wed Oct  9 04:44:42 2024]
Finished job 267.
126 of 482 steps (26%) done
[Wed Oct  9 04:46:11 2024]
Finished job 321.
127 of 482 steps (26%) done
[Wed Oct  9 04:47:30 2024]
Finished job 483.
128 of 482 steps (27%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error messagecd

**Comment by huddlej** [comment]
Hi @Kritchyyui, can you share the full Snakemake log file as an attachment to this issue? It looks like the snippet of the log above doesn't include the actual error message. This is a common issue when running Snakemake with multiple simultaneous jobs where the error message can appear farther away from the rule that errors. The path to the full Snakemake log should appear at the end of the output after the workflow fails (usually it is in the `.snakemake` directory).

**Comment by Kritchyyui** [comment]
Hi @huddlej , it is snakemake log file as attachment.
 
[2024-10-09T042551.840811.snakemake.log](https://github.com/user-attachments/files/17319828/2024-10-09T042551.840811.snakemake.log)

Thank you for your help,
Kritchyyui

**Comment by huddlej** [comment]
Thank you, @Kritchyyui! That log file at least confirms that there isn't an explicit error message anywhere else in the output. 😅 

Can you try running the workflow again but with a single job at once (e.g., with Snakemake's `-j 1`) and also keep an eye on your system's memory use while the refine step is running? I've had a similar issue before when running multiple `augur refine` instances at once where those instances use up all of my available memory causing the jobs to be killed without any meaningful error message.

**Comment by Kritchyyui** [comment]
My apologies for the misunderstanding. I noticed a message indicating a missing file during the process. Afterward, a red-colored error message appeared before the run stopped. I am also using Docker to run Nextstrain, and my system memory is being utilized for this. Thank you very much for your suggestion.
