### ISSUE TITLE
Can we migrate this repository to nextstrain/norovirus?

### ISSUE THREAD

**Issue by j23414** [blab/norovirus#2]
[Slack context linked here](https://bedfordlab.slack.com/archives/C0K3GS3J8/p1727373954503549?thread_ts=1727373130.162819&cid=C0K3GS3J8)

[added later]
Further back [slack context](https://bedfordlab.slack.com/archives/C0K3GS3J8/p1726259695948139).

**Comment by huddlej** [comment]
We could use this repo as the base for a new Nextstrain repo, but I wouldn't copy this repo as it is. This repo depends on [manually curated Genome Detective annotations](https://github.com/blab/norovirus/tree/main/data), so the workflow is not fully automated. It is also using the older style repo layout and would need some focused developer effort to migrate to the new style (e.g., moving [hardcoded values](https://github.com/blab/norovirus/blob/a048222a676e0eb77602a9ecb726d64ca7a86db3/Snakefile#L88-L93) to a config file, adding an ingest from NCBI, verifying time tree settings, etc.).

@kistlerk Do you have any concerns/thoughts about migrating this repo to an official Nextstrain build?

**Comment by j23414** [comment]
> use this repo as the base for a new Nextstrain repo

Exactly, I fully envision this as a starting point (not the end point) of a norovirus repo. We have a pretty standard path to modify an existing pathogen repo to conform to the pathogen-repo-guide (as we've done for dengue, wnv, lassa, yellow-fever, measles, etc...).

That said, any concerns/thoughts welcome! Would new sequences that do not have fields from the manually curated Genome Detective annotations cause the phylogenetic build to fail? Happy to look into a work-around if that is the case.

**Comment by kistlerk** [comment]
I haven’t ever compiled a Nextclade reference tree, but could that be used to assign genotypes?

**Comment by j23414** [comment]
I don't see why not (instead of [appending Genome Detective columns](https://github.com/blab/norovirus/blob/a048222a676e0eb77602a9ecb726d64ca7a86db3/Snakefile#L42-L67))... I was about to say we could use the current tree in a Nextclade dataset but we may need to `--include-root-sequence-inline` during the [export step](https://github.com/blab/norovirus/blob/a048222a676e0eb77602a9ecb726d64ca7a86db3/Snakefile#L253-L259)

<img width="860" alt="Screenshot 2024-10-10 at 4 40 53 PM" src="https://github.com/user-attachments/assets/d943a11b-9e51-4c15-a305-c0723a2b1b82">

Would compiling a Nextclade reference tree be something you're interested in doing? I'm happy to provide guidance and support.

**Comment by j23414** [comment]
@huddlej, would it be more acceptable to mirror this repository to `github/nextstrain/norovirus`? This way a `blab/norovirus` repo is kept for historical purposes?

**Comment by huddlej** [comment]
Yes, it seems useful to keep this repo as a historical document of Allison's internship project. Once the official Nextstrain repo is setup, I would link to that repo from this repo's README and then probably archive this repo.

**Comment by j23414** [comment]
Mirrored, thanks all for the discussion!

* https://github.com/nextstrain/norovirus
